# --- Change what appears in the banner and meta data of your pages --- #
title: My Language Learning Website
description: This is the tag-line of my website.

# --- Specify the language of site --- #
lang: en

# --- List of pages in your site --- #
# --- Only change these if you change the name of your .md files --- #
# --- And, only change the names of the HTML files named after each colon: e.g. page2.html --- #
github:
  page1: index.html
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  
# --- List of links in the navigation bar --- #
# --- Change the words after the colons to change your navigation labels --- #
navbar-links:
  page1: Home
  page2: Vocabulary
  page3: Grammar
  page4: Listening
  page5: Explore more
